const AboutPage = () => {
    return (
        <>
            <div style={{ height: "95vh", width: "100vw", overflowX: "hidden" }} className="bg-gray-700 w-max h-max items-center justify-center text-center">
                <h1 className="text-lime-50 text-xl underline underline-offset-2 mt-8">ABOUT PAGE :</h1>
                <p className="text-lime-50 font-thin mx-40 mt-10">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia minima labore numquam accusamus sequi natus, quis, eum repudiandae rephenderit totam qui sapiente minus assumenda accusantium, voluptatum possimus pariatur autem deserunt!
                    Pariatur voluptas explicabo officia mollitia quo, cumque consequuntur error? Consequatur at sapiente nostrum unde explicabo eum beatae modi velit nisi, accusamus suscipit sit culpa molestias obcaecati cum qui, rephenderit dolorem!
                    Odio animi esse fugit eos, cumque sint eveniet perferendis voluptates recusandae ipsam porro distinctio. Veniam inventore beatae iure rerum corrupti, quidem error numquam commodi! Ipsam labore dolorum quibusdam repellat beatae!
                    Totam facilis, eos quo, iste laudantium odit provident inventore accusamus consectetur aperiam praesentium quibusdam quis, minus labore tempore rem hic quasi. Doloremque ullam est quis iure ipsa natus facilis minima?
                    Soluta similique autem quidem enim dignissimos eos vitae dolorum magnam officia quibusdam, beatae quaerat molestias vero vel quae aliquid quisquam. Atque fugit minus vero numquam veniam perferendis totam accusamus voluptas.
                    A nam dolore quo excepturi porro libero in natus maiores dicta distinctio labore laborum suscipit, voluptatibus corporis quisquam non vel iure. Ullam doloribus totam ab, ipsa et natus voluptate eaque?
                    Consectetur, alias. Sequi ad ipsum facilis magni cum assumenda neque pariatur non necessitatibus est et qui in exercitationem consequuntur iure, ea ipsa, voluptate repellat! Minus corrupti cupiditate nulla laboriosam exercitationem!
                    Fugit dignissimos, aperiam facilis nihil molestias eaque earum sequi vel soluta deserunt minima libero exercitationem delectus amet impedit quas maxime vitae quaerat a? Culpa quam impedit similique hic libero incidunt!
                    Distinctio non fuga molestias porro perspiciatis sed error, quasi aliquam delectus, est ullam. Aperiam quos eligendi eaque nemo, rephenderit earum ea atque sed quisquam iste harum asperiores labore temporibus voluptatibus!
                    Ab, laudantium ipsum? Aliquam natus maiores iusto, eum quis ipsum modi quia nulla qui! Laborum magnam aspernatur voluptas repellat suscipit beatae incidunt atque aliquid a vitae, quibusdam, iste maiores nihil?
                    Quisquam est officia sint ut quidem molestiae ad voluptatibus accusantium ipsam voluptatum nulla laborum non architecto dolores id consectetur tempore vitae laboriosam aperiam dignissimos earum quia voluptas, nostrum odit? Cum.
                    Fuga, nobis magnam provident, officiis, repudiandae at doloremque dicta quos voluptatem odio quaerat veniam autem non sed rerum maiores voluptatum corporis sint minus? Natus maxime et accusantium dignissimos, esse commodi!
                    Consectetur totam quos officiis. Similique assumenda voluptas repudiandae perferendis officiis eos ex a iste, illo, dicta laboriosam reiciendis quos nesciunt voluptatum rem veniam placeat soluta consequatur dolor accusamus debitis quidem.
                    Dolor, doloribus animi voluptates enim corporis ut dignissimos dolorum sint consequuntur modi ratione dolorem voluptatem debitis repellendus quibusdam necessitatibus, quas quia nam aliquam aliquid esse inventore quos deserunt commodi. Quos!
                    Atque magnam repudiandae distinctio non? Libero odio repudiandae asperiores ipsum quis nihil qui vel repellat, velit aperiam aut quisquam quo? Veritatis est nam qui impedit rerum doloribus provident nobis quaerat!
                    Eos, aspernatur maxime? Hic quidem doloribus nostrum temporibus quam corrupti numquam praesentium vero nisi at! Sunt repellat laborum voluptatibus nesciunt magnam, voluptas, a ab quisquam minima possimus magni optio repudiandae?
                    Veritatis cum saepe deserunt consequuntur, sequi deleniti molestias optio alias tenetur culpa pariatur neque quidem aut necessitatibus excepturi quo, modi, consequatur sed eaque beatae adipisci ratione expedita. Nihil, ducimus vel!
                    Repellendus, quidem molestias omnis excepturi officiis fuga culpa libero autem voluptatem, vero amet sunt aperiam rephenderit necessitatibus rerum praesentium nisi eius aliquam fugiat nulla maxime! In quae nulla soluta laudantium.
                    Fuga quibusdam temporibus, omnis vitae nemo quos! Ipsa minus, cum dolorem voluptatibus consequuntur architecto quisquam? Nam, distinctio labore. Libero adipisci quisquam praesentium repudiandae, nam suscipit omnis repellendus animi numquam consectetur?
                    Ipsa optio asperiores rem, nam officiis iste ut at dicta. Ducimus sapiente animi itaque praesentium minus numquam aut beatae quos ab autem neque cupiditate, voluptatem perspiciatis. Ad repellat voluptatem ducimus.
                    Necessitatibus porro inventore fuga, ea illum itaque hic voluptatem quo sed quisquam iure ullam eveniet officiis labore at! Suscipit dolorem obcaecati saepe. Obcaecati, repellendus eveniet? Magnam doloremque non odio minima?
                    Blanditiis iure ipsum veniam accusamus sequi quidem doloribus? Vel temporibus quaerat harum corporis delectus rephenderit, quibusdam inventore voluptatibus magni cupiditate nostrum voluptate, molestiae excepturi atque dicta in nobis natus minus!
                    Quae qui quam, facere omnis quia cumque quod voluptates autem ea consequuntur, at, sed possimus alias veniam mollitia. Magni at praesentium nulla quibusdam. Nihil rerum deserunt, vel quaerat eligendi odit.
                    Ratione ad error quidem voluptatibus? Quam molestiae asperiores vitae incidunt, optio at reiciendis mollitia ipsam nemo nihil, a voluptas. Quasi deserunt rerum possimus aliquam est vel architecto quos asperiores eos!
                    Perferendis voluptas labore at dolor placeat quibusdam. Omnis non totam rephenderit saepe atque quaerat tempora iusto molestias expedita quas? Sequi soluta recusandae aspernatur expedita, ullam et deserunt libero necessitatibus iure.
                    Corporis, quibusdam quod? Dolor quas libero molestiae sapiente, exercitationem doloremque expedita deleniti, maiores cumque hic autem consequatur ullam nihil non esse beatae unde fugiat. Dolore aliquam iusto iure in adipisci!
                    Quod nobis placeat necessitatibus tempore qui. Fugiat amet debitis eos voluptatum asperiores in repellat cum excepturi velit, quidem sit alias qui aut! Quasi quos, voluptate ducimus labore in nostrum esse!
                    Earum harum officiis ab totam cumque repellendus fuga a amet, dolorum, esse minus aspernatur natus. Eius libero, recusandae porro architecto eaque suscipit, ex autem consequatur laboriosam vero alias atque rerum!
                    Exercitationem, eum aut expedita quibusdam magni ratione omnis itaque laudantium sed labore culpa corrupti beatae officia, asperiores iure accusamus tempore, dignissimos delectus tenetur corporis blanditiis error eligendi. Laborum, cupiditate distinctio!
                    Rerum, sit! Totam veritatis maxime nesciunt perferendis neque nostrum dolore quidem quis ipsum sed cumque nulla ex inventore tempora dicta quo facere, ipsa possimus? Tenetur repudiandae dicta tempora doloremque nulla.
                    Laborum nesciunt error eaque voluptas at maiores, commodi facere recusandae unde minus pariatur? Numquam accusamus est culpa autem quo quasi quis sunt sapiente, minus rephenderit officia totam odio maiores. Incidunt.
                    Est non odio voluptatem sunt labore quidem necessitatibus cumque voluptatibus dolorum alias, aperiam ipsum blanditiis! Voluptate accusamus placeat enim praesentium sit, error ab, molestiae labore quod fuga rem maiores quos!
                    Temporibus modi ipsam dolorem qui magnam quam voluptatibus quo mollitia aperiam facilis, cum alias in! Impedit dolorem explicabo, ipsum dolores eveniet optio neque, velit placeat distinctio veritatis in voluptate incidunt?
                    Quibusdam minima perspiciatis numquam magnam, rem pariatur voluptates. Soluta, nostrum! Saepe ad amet delectus quisquam eaque necessitatibus, magnam praesentium exercitationem dolores rerum! Omnis perspiciatis sit tempora ducimus itaque eius assumenda!
                    Ea id veniam ipsa omnis! Aperiam iste itaque nulla soluta a esse culpa, voluptatum voluptates nam neque eveniet explicabo dolorem deserunt eligendi porro cum ea necessitatibus numquam libero debitis aliquid!
                    Praesentium minus explicabo molestiae itaque eius maxime incidunt quam cupiditate nesciunt. Harum velit deserunt labore temporibus sit illum aliquid, placeat iusto, quam perspiciatis officiis, commodi illo ea? Dolorum, placeat rephenderit.
                    Quaerat alias ex unde, fuga sunt molestias sequi fugit aliquam a, eius corrupti voluptate totam harum odit doloremque dolorum ratione quo repudiandae magni maxime, soluta eligendi? Quis illo pariatur est!
                    Expedita unde necessitatibus vel placeat illo nesciunt quos alias aliquid optio pariatur earum ea, neque consectetur commodi laborum assumenda libero asperiores nemo corrupti eveniet minima. Adipisci fugit rephenderit sunt cum?
                    Incidunt sequi saepe alias aliquam molestiae corporis pariatur eos, qui dolorum facere consequuntur rephenderit iste obcaecati velit ducimus quidem excepturi sint possimus porro vel tenetur. Labore debitis quae soluta sit?
                    Eos distinctio consequuntur inventore at a, repellendus ea veniam, nihil explicabo nemo in perspiciatis, dolore neque quos dignissimos tempora ipsum sed rerum ab fugiat ipsa amet eius! Sit, rerum culpa.
                    Fuga iste quidem tempore, dignissimos nesciunt suscipit! Vero saepe ducimus aliquam recusandae voluptatem nemo enim, exercitationem natus. Temporibus natus deserunt asperiores veniam veritatis repellendus nihil. Expedita in quaerat non dolores.
                    Adipisci, porro beatae eos officiis accusantium in distinctio rerum deleniti minus recusandae delectus corrupti tempora soluta nihil perspiciatis quas mollitia sint, totam quisquam voluptas! Enim aspernatur minima praesentium aliquid est.
                    Modi repudiandae expedita asperiores eos, earum voluptatibus ex. Iure distinctio, numquam magnam adipisci cupiditate qui. Eaque amet voluptatibus suscipit. Placeat, ullam labore? Laborum odit vel tempore deserunt corporis velit debitis!
                    Ducimus obcaecati officia omnis fugiat cum maiores autem perspiciatis eius saepe id, dolor voluptatibus. Dolorum in, amet quisquam minus exercitationem inventore. Saepe odit, qui facilis nesciunt eum corrupti tempora beatae.
                    Dolore alias laborum, dolor qui aliquam quasi corporis praesentium saepe eum adipisci non voluptatem fuga, mollitia, repudiandae est minima ab expedita corrupti consequatur vero culpa doloremque eveniet iusto? Animi, nesciunt!
                    Minima a quaerat repudiandae laborum quos quam alias excepturi molestias laudantium, corporis ex optio sit rerum doloribus deserunt quibusdam mollitia dolores pariatur libero saepe consequuntur facere consectetur. Dignissimos, laboriosam quod.
                    Quas quasi maxime, alias quos explicabo hic assumenda pariatur quibusdam harum doloribus a, sint eligendi reiciendis minus dolores sequi saepe, cumque at laudantium dignissimos beatae voluptatibus dolor totam! Recusandae, eos!
                    Iste quis dignissimos cupiditate incidunt id! Dolores illo id quam architecto quod porro dolorum iure quos laudantium, voluptatum suscipit repellendus eum repellat culpa non. Quibusdam magni ducimus veritatis eos aliquid!
                    Nulla ab ratione voluptate illum odit harum in illo unde, corporis tenetur! Quas nam facilis inventore minima nobis totam nostrum. Repellat esse ipsam nobis. Quod, cupiditate voluptas! Magni, excepturi facilis!
                    Ullam cumque itaque odit vel autem quod aliquid, necessitatibus numquam, sapiente nobis officia praesentium quibusdam! Repellendus ea, eius soluta porro, explicabo hic non quia quos saepe exercitationem quidem cum natus?
                    Eum ipsum maiores animi magni doloremque ea ad cupiditate nulla, enim dignissimos. Modi beatae placeat ipsum iste debitis suscipit nostrum. Cumque ut molestias esse beatae sit labore unde excepturi quibusdam?
                    Totam nesciunt debitis quo cum ullam in quidem. Provident asperiores voluptatem facere sequi nobis aut eius, quos ipsam, nihil cum, officiis debitis enim. Magnam sapiente facere soluta aliquid quae rephenderit?
                    At rephenderit ad animi excepturi facilis eos sunt fuga sapiente molestiae ipsa repudiandae hic, harum, possimus accusantium dignissimos cumque placeat. Minus in exercitationem blanditiis molestiae doloribus adipisci perspiciatis nesciunt quis.
                    Quibusdam facere quas corrupti laudantium aliquid beatae delectus molestiae, aspernatur dolorem error fugiat cupiditate sit maiores tempore adipisci sed laborum facilis minus recusandae quisquam ipsa quod in voluptatum ducimus. Aliquam!
                    Officia dolorem, quos blanditiis placeat veritatis, eum maiores at eaque dolorum quidem distinctio natus quibusdam fugit, eveniet voluptates nemo quo nihil dignissimos. Ipsam quaerat reiciendis praesentium consectetur voluptates similique consequatur.
                    Officia, maiores quisquam. Rerum ut ab voluptatibus at, in fugiat aspernatur molestiae quae magnam est, esse minus eveniet debitis, repellat sapiente animi! Laboriosam alias delectus earum, ad numquam at quae.
                    Quaerat, possimus accusamus. Impedit obcaecati rerum exercitationem placeat sunt saepe dolorum! Amet aperiam similique, optio dolore totam rerum voluptates magnam facilis atque quidem nobis a nostrum. Eum amet temporibus alias.
                    Ea, quidem repudiandae. Repellat quod error voluptas perspiciatis nam illum cumque excepturi explicabo quae tenetur? Officia nam numquam, doloremque exercitationem nostrum porro illo! Aspernatur itaque voluptate suscipit in, veniam cumque!
                    Voluptate aliquam temporibus dolore, harum dolorum ratione quod! Vel inventore temporibus consequatur nesciunt praesentium hic mollitia eligendi modi asperiores beatae. Officiis optio labore cupiditate asperiores rem, doloremque repudiandae non laboriosam.
                    Laudantium facere dignissimos eius rephenderit! Quidem tempora, commodi eius quibusdam iusto sint iste a perspiciatis totam accusamus reiciendis repellendus asperiores iure dolores. Illum facere eaque ducimus unde quos officia sunt.
                    In fugit eos ab rerum magnam repudiandae officia corporis, deleniti id fuga non alias doloremque voluptates, aliquid vero quos quasi animi dolore. Deserunt quod veritatis rem consequatur amet eveniet molestiae?
                    Quasi fuga minus temporibus, esse quis accusantium perspiciatis animi, dolore ullam molestias distinctio nam. Unde ratione praesentium magnam ipsum veniam reiciendis, atque impedit sunt quibusdam, laborum quisquam quasi quos in.
                    Quod dolorem rerum corporis soluta culpa nostrum aspernatur labore commodi quisquam animi atque dolor enim, doloribus velit impedit nisi repellat, sint natus. Error dicta porro facere esse fuga quia. Illo.
                    Aliquam maxime deserunt voluptate! Accusantium odio temporibus maxime esse quos explicabo, ex officia dolores ad ab similique, dolorum rephenderit ipsa mollitia exercitationem voluptatem voluptas natus sequi? Distinctio rem non neque.
                    Doloribus, vitae similique! Quo quasi ea, ipsum error deleniti quibusdam odit totam accusamus pariatur, quis illum? At laborum, voluptatum vero veritatis temporibus nemo libero blanditiis sit consequuntur! Quia, atque blanditiis?
                    Explicabo, vel deleniti nostrum repellat possimus praesentium perspiciatis officia amet quibusdam corrupti accusamus sit est quis numquam animi aliquid voluptate dicta delectus dignissimos esse atque placeat id provident reiciendis. Incidunt?
                    Facere porro similique eos ad earum hic at atque quaerat. Unde, odio? Aliquid minima tempore nobis dolorem iure itaque doloribus autem quibusdam molestiae harum, deleniti culpa sint assumenda quia quae?
                    Officiis beatae molestiae rerum reiciendis id deserunt porro voluptatem magnam, est consequatur recusandae possimus, voluptas ab perspiciatis nostrum. Consequatur autem tempore incidunt necessitatibus quae architecto exercitationem praesentium esse omnis eveniet!
                    Mollitia error explicabo consequatur delectus autem aut quas quaerat provident dicta commodi, facilis rerum ducimus nam sint et cumque fugit vel vero quia optio adipisci tenetur pariatur! Hic, excepturi accusantium.
                    Natus maxime mollitia aperiam numquam quia commodi suscipit quo dolore rem dolor, alias quaerat nemo eum quibusdam in voluptates accusamus ex corrupti laudantium excepturi non, sequi ut. Id, voluptas. Impedit.
                    Eum, obcaecati ab repellendus atque deserunt aut, non voluptates aspernatur mollitia libero deleniti nostrum odio unde ullam quod aliquam. Eaque illo error iure maiores ullam veniam, delectus autem aut aliquam!
                    Unde saepe enim blanditiis! Alias odio fugiat facilis eligendi officiis provident quo quibusdam expedita officia et aperiam illo, maxime placeat accusamus, voluptates enim consequuntur? Expedita, explicabo. Perspiciatis repellat mollitia explicabo.
                    Rerum ut alias ex quisquam nostrum, incidunt voluptatibus doloremque, blanditiis cumque esse exercitationem officia. Sed modi obcaecati a est nemo magni repudiandae totam corrupti soluta facere ipsum, quibusdam illo architecto.
                    Aut et nisi quia iure architecto maxime earum ipsum eveniet distinctio atque mollitia illum dicta quisquam, nam ipsam provident enim molestias blanditiis a quasi. Et obcaecati beatae quibusdam itaque soluta.
                    Expedita nemo aliquam libero? Porro nihil ad deserunt dolorem optio? Saepe esse harum corporis molestiae explicabo commodi nisi assumenda unde ab expedita ad, perspiciatis nobis officia, officiis fugiat? Fugit, expedita.
                    Voluptates tenetur dolorem rem corporis dignissimos culpa aliquid impedit quam, ut ducimus! Ipsum, alias dolores dolorum iste reiciendis animi quas possimus perspiciatis mollitia velit, impedit, deleniti minima? Ad, et numquam?
                    Et, illum labore dolorum, quam consequatur quod, aperiam temporibus nostrum odio aliquid perspiciatis asperiores voluptas obcaecati dicta ipsam ab! Veniam repudiandae autem perspiciatis. Placeat iusto ducimus hic. Enim, totam consequatur.
                    Autem veniam, eum id recusandae eligendi aut totam libero dolor, dolore minus nostrum illo beatae, enim deleniti magnam culpa unde amet facere necessitatibus quibusdam. Fuga, asperiores impedit? Exercitationem, illo nostrum?
                    Inventore, alias nam vel, sint quisquam atque possimus modi qui magnam nesciunt molestiae expedita, deleniti iste accusamus eaque totam quas! Facilis fugiat, adipisci ratione vitae fuga dolorum modi expedita quas?
                    In saepe consectetur odio nobis! Non iste nobis laborum voluptates dicta dignissimos dolor enim eligendi eaque fuga cum, praesentium animi autem, impedit quidem aspernatur ad quos. Eaque vel tempora possimus.
                    Adipisci harum at ex qui perferendis nulla sequi, vel laudantium iste consectetur delectus distinctio esse itaque. Maiores facilis nulla consectetur sapiente repellat mollitia dolor blanditiis, vitae modi incidunt, cum pariatur.
                    Deserunt a voluptate sint beatae corporis eos illo officiis iste possimus, tempora esse, unde magnam quidem laborum perspiciatis? Eaque, illo sequi. Vitae corporis inventore, natus sint blanditiis eveniet voluptatibus? Unde.
                    Deleniti quia distinctio, accusantium ipsam ab quaerat dolor alias id adipisci, deserunt harum dicta voluptatem molestiae fugiat excepturi non ducimus iure blanditiis, voluptas sint nobis impedit quam? Repellendus, saepe natus.
                    Et quae soluta sint. Perspiciatis quibusdam nam consectetur officiis aliquam adipisci voluptatem cumque culpa, delectus veniam ad temporibus animi dolore magni eum aperiam possimus. At laudantium molestiae dolores velit consequuntur.
                    Culpa inventore quibusdam pariatur quia, alias optio odio architecto vel voluptatibus ipsa nemo fugiat. Soluta ea qui, consequatur unde in, fuga explicabo temporibus illum vel impedit maxime id voluptatem aliquam.
                    Nam accusantium repellat quae. Repellat illum explicabo debitis, accusantium officia ut vero rerum odio? Veritatis, repellat! Ipsum quas libero tempora facere? Molestiae consequuntur sed fugit incidunt veritatis possimus voluptatem impedit.
                    Quidem, veritatis? Sapiente deleniti consectetur quibusdam! Nihil qui cumque, rerum facilis temporibus ratione! Enim distinctio maxime ipsam neque atque odio voluptatum. Veritatis accusantium, laudantium corrupti quasi ipsa ducimus ut optio?
                    Distinctio, et laudantium nisi explicabo optio adipisci nihil dolorem ab magni accusamus quae facilis a sapiente provident illum animi doloremque in labore atque illo eaque odit impedit nobis? Eum, necessitatibus?
                    Maiores et eveniet quos cum cumque, assumenda, magnam dicta excepturi debitis distinctio, repellat sed laboriosam illo ipsam consequuntur architecto sint inventore. Tempore unde vitae cum id, eaque numquam sit sed!
                    Sed, delectus esse consequuntur illo eos quae tempore cupiditate rem quidem quos voluptate molestiae temporibus, eum sequi eaque sit unde odio officia nam. Alias officiis exercitationem accusamus cupiditate eaque libero.
                    Tempora, est rem voluptate iste corporis esse sint dolorum sed saepe atque eveniet, facere sequi. Commodi minus repellat distinctio unde cupiditate quis optio magni veniam tempore? Nam sequi placeat architecto.
                    Quibusdam, molestias tenetur accusamus voluptatem totam numquam reiciendis! Quo doloribus cupiditate dolores, beatae ab officiis porro! Similique ea ducimus delectus dolore animi illo provident nemo, eos iusto inventore totam repellat.
                    Eaque, obcaecati nihil explicabo saepe neque sequi rerum ducimus fugiat accusantium, id, vitae modi. Esse obcaecati repellat recusandae id dolor beatae, pariatur odit officiis similique et reiciendis iusto quisquam. Consectetur.
                    At autem provident nisi dolor laudantium excepturi voluptate, doloribus impedit nobis voluptatum cum nihil? Ipsum earum explicabo perferendis ipsam recusandae, ab modi, dolor illo ullam similique vitae tenetur obcaecati ducimus.
                    Labore, dicta provident laudantium nulla qui fugiat, temporibus, quos cum dolorum voluptatum aliquam? Possimus tempore quasi culpa sapiente voluptas expedita fuga ea praesentium aliquid, accusamus deserunt beatae labore animi facilis.
                    Illum veniam repellat reiciendis, eveniet recusandae numquam nemo excepturi modi odit nam maxime quam saepe et delectus voluptas tempora voluptate rem nostrum, dolores pariatur adipisci incidunt nulla corrupti eos. Quasi!
                    Architecto quae, in esse harum praesentium excepturi expedita non repellat deleniti pariatur facilis dolore minima ea quo doloribus optio aliquam maiores distinctio, eum facere, eos mollitia blanditiis? Nisi, laudantium neque.
                    Sunt ut aut in cupiditate laudantium laborum dolor tempore corporis soluta alias! Corrupti ratione obcaecati consequuntur omnis quas culpa dignissimos dolorum, placeat odio. Doloremque esse amet at soluta? Eaque, facilis.
                    Sapiente dolorem, voluptas nostrum voluptate quo voluptates minus veniam totam autem eligendi, ad deserunt at accusamus sit error architecto nihil voluptatibus quis delectus aut fugiat pariatur, cumque nobis. Odio, corrupti.
                    Fugit modi laborum earum asperiores molestiae. Velit voluptatum nisi ab consectetur, magnam illo officia voluptate itaque dolores ea maxime facilis nulla suscipit dignissimos aspernatur eum nemo saepe rephenderit animi expedita.
                </p>
            </div>
        </>
    )
}

export default AboutPage